import type { Severity } from "../core/model.js";
import { countBySeverity, type ReportData } from "./data.js";

const SEVERITY_ICON: Record<Severity, string> = { error: "🔴", warn: "🟡", info: "🔵" };

export function renderMarkdown(data: ReportData): string {
  const lines: string[] = [];
  const counts = countBySeverity(data.findings);

  lines.push("# ctxlint report");
  lines.push("");
  lines.push(`**Context Health Score: ${data.score.total}/100**`);
  lines.push("");
  lines.push("| freshness | uniqueness | consistency | budget | structure |");
  lines.push("|---:|---:|---:|---:|---:|");
  const s = data.score.subscores;
  lines.push(`| ${s.freshness} | ${s.uniqueness} | ${s.consistency} | ${s.budget} | ${s.structure} |`);
  lines.push("");
  lines.push(
    `${data.stats.surfaces} context file(s), ${data.stats.rules} rules. Token counts: ${data.tokenNote}.`,
  );
  lines.push("");

  lines.push("## Context files");
  lines.push("");
  lines.push("| file | kind | scope | tools | tokens≈ | rules |");
  lines.push("|---|---|---|---|---:|---:|");
  for (const surface of data.surfaces) {
    const tokens =
      surface.tokensExact !== undefined
        ? `${surface.tokensExact} (exact)`
        : `≈${surface.tokensEstimated}`;
    lines.push(
      `| \`${surface.path}\` | ${surface.kind} | ${surface.scope} | ${surface.tools.join(", ") || "—"} | ${tokens} | ${surface.ruleCount} |`,
    );
  }
  lines.push("");

  lines.push("## What each tool loads");
  lines.push("");
  for (const context of data.effectiveContexts) {
    if (context.entries.length === 0) continue;
    const conditional =
      context.conditionalTokensEstimated > 0
        ? ` (+ ≈${context.conditionalTokensEstimated} conditional)`
        : "";
    lines.push(
      `### ${context.tool} @ \`${context.directory}\` — ≈${context.totalTokensEstimated} tokens always-on${conditional}`,
    );
    lines.push("");
    lines.push("| # | file | tokens≈ | why |");
    lines.push("|---:|---|---:|---|");
    for (const entry of context.entries) {
      lines.push(
        `| ${entry.order} | \`${entry.path}\` | ≈${entry.tokensEstimated} | ${entry.reason}${entry.conditional ? " *(conditional)*" : ""} |`,
      );
    }
    lines.push("");
  }

  lines.push(
    `## Findings (${counts.error} error, ${counts.warn} warning, ${counts.info} info)`,
  );
  lines.push("");
  if (data.findings.length === 0) {
    lines.push("No findings — this is a healthy setup.");
    lines.push("");
  }
  for (const finding of data.findings) {
    lines.push(`- ${SEVERITY_ICON[finding.severity]} **[${finding.category}]** ${finding.message}`);
    for (const evidenceLine of finding.evidence.split("\n")) {
      lines.push(`  > ${evidenceLine}`);
    }
    if (finding.fix) lines.push(`  - fix (${finding.fix.kind}): ${finding.fix.description}`);
  }
  lines.push("");
  lines.push(`*Generated by ctxlint. Token counts are estimates unless marked exact.*`);
  lines.push("");
  return lines.join("\n");
}
